apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.wp.image }} 
  labels:
    app: {{ .Release.Name }}-{{ .Values.wp.image }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.wp.image }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.wp.image }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.wp.image }} 
          image: {{ .Values.wp.image }}:{{ .Values.wp.tag }}
          env:
            - name: WORDPRESS_DB_HOST 
              value: {{ .Release.Name }}-db-svc:{{ .Values.db.port }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret-mysql
                  key: password
            - name: WORDPRESS_DB_NAME
              value: {{ .Release.Name }}-{{ .Values.db.name }}
            - name: WORDPRESS_DB_USER
              value: root 
          ports:
            - containerPort: 8080
              protocol: TCP
