apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-svc
spec:
  ports:
  - name: db-port
    port: {{ .Values.db.port }}
    protocol: TCP
    targetPort: {{ .Values.db.port }}
  selector:
    app: {{ .Release.Name }}-{{ .Values.db.image }}
  clusterIP: None
