apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wp-svc
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-{{ .Values.wp.image }}
  ports:
    - port: 80 
      targetPort: 80
